---
# https://www.tikalk.com/posts/2017/02/21/testing-ansible-with-kitchen/
driver:
  # https://github.com/test-kitchen/kitchen-docker
  name: docker
  #name: dokken
  chef_version: latest
  # enable cachier so we don’t need to re-download repo update multiple times.
  cachier: true
  # This determines if Docker commands are run with sudo
  # The default value depends on the type of socket being used. For local sockets, the default value is true. For remote sockets, the default value is false
  # This should be set to false if you're using boot2docker, as every command passed into the VM runs as root by default.
  # use_sudo=false

platforms:
 - name: ubuntu-16.04 # works fine

provisioner:
  name: ansible_playbook
  ansible_verbose: true
  ansible_verbosity: 1
  ansible_version: latest
  idempotency_test: true
  require_chef_for_busser: false
  always_update_cookbooks: true
  playbook: roles/githubfoam.openvswitch/tests/test.yml
  hosts: all
  additional_copy_path:
    - "."

verifier:
  # use default verifier by test kitchen, inspec
  name: inspec

suites:
  - name: default
    run_list:
      - recipe[git_cookbook1::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
