---
language: ruby
rvm:
  #- 2.3
  - 2.5
sudo: required
env:
  global:
   - distribution=ubuntu
     version=18.04
   - COMMIT=${TRAVIS_COMMIT::8}
  matrix:
    - INSTANCE=default-ubuntu-1604
  #   - INSTANCE=default-centos-74
services:
  - docker
before_install:
  - curl -L https://www.getchef.com/chef/install.sh | sudo bash -s -- -P chefdk -v 3.5.13
  - eval "$(/opt/chefdk/bin/chef shell-init bash)"
  - rvm version
jobs:
  include:
    - stage: Continuous Integration Step, white box SAST etc tests
    # https://github.com/zuazo/kitchen-in-travis-native/issues/1#issuecomment-142455888
      before_script:
        - sudo iptables -L DOCKER || sudo iptables -N DOCKER
      script:
        # Create a random file to store the container ID.
        - chef --version
    - stage: Continuous Delivery Step, black box DAST etc tests
      script:
        # DODCKER_TOKEN must be entered travis website -> repository -> settings -> environment variables
        - chef exec ruby --version
    - stage: Continuous Deployment Step, one button to deploy docker image
      script:
        # DODCKER_TOKEN must be entered travis website -> repository -> settings -> environment variables
        - echo "success"
after_success:
    - stage: Workflow ends
      script:
        - echo "success"
# Notify Ansible Galaxy when an ansible role builds successfully.
notifications:
  #email: false
   email:
     on_success: never # default: change
     on_failure: always # default: always
   webhooks: https://galaxy.ansible.com/api/v1/notifications/
